version: '3.7'

services:
  vott:
    build:
      context: .
      args:
        - CORTEXIA_VERSION=${CORTEXIA_VERSION}
        - ENVIRONMENT=${ENVIRONMENT}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_INSTRUMENTATION_KEY=${REACT_APP_INSTRUMENTATION_KEY}
        - NODE_ENV=${NODE_ENV}
    image: cortexia/vott:${DOCKER_TAG}
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=$(TRAEFIK_PUBLIC_NETWORK)"
        - "traefik.http.routers.vott.entrypoints=websecure"
        - "traefik.http.routers.vott.tls.certresolver=cloudflare"
        - "traefik.http.routers.vott.rule=Host(\`$(SUBDOMAIN).$(DOMAIN)\`)"
        - "traefik.http.services.vott.loadbalancer.server.port=3000"

