version: "3.3"
services:
  vott:
    build:
      context: .
      args:
        - CORTEXIA_VERSION=${CORTEXIA_VERSION}
        - ENVIRONMENT=${ENVIRONMENT}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_INSTRUMENTATION_KEY=${REACT_APP_INSTRUMENTATION_KEY}
        - NODE_ENV=${NODE_ENV}
    image: cortexia/vott:${DOCKER_TAG}
    environment:
      - PUBLIC_URL=https://${SUBDOMAIN}.${DOMAIN}
      - CORTEXIA_VERSION=${CORTEXIA_VERSION}
    deploy:
      labels:
        - traefik.frontend.rule=Host:${SUBDOMAIN}.${DOMAIN}
        - traefik.enable=true
        - traefik.port=3000
        - traefik.tags=${TRAEFIK_PUBLIC_TAG}
        - traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
