version: "3.3"
services:
  vott-dev:
    build: 
      context: ./
      dockerfile: Dockerfile-dev
    env_file:
     - ./.env
    volumes:
      - ./src:/app/src
    ports:
      - "$DEV_VOTT_PORT:3000"
