version: '3.7'

services:
  vott-dev:
    build: 
      context: ./
      dockerfile: Dockerfile-dev
    env_file:
      - ./.env
    environment:
      - STACK_NAME=vott
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
