FROM node:10.16.3-alpine

ADD . /tmp
WORKDIR /tmp

RUN npm install -g serve

RUN npm ci \
    && npm run build

ARG REACT_APP_INSTRUMENTATION_KEY=app-key
ARG REACT_APP_API_URL=https://backend.cortexia.io
ARG NODE_ENV=production
RUN echo "REACT_APP_INSTRUMENTATION_KEY=$REACT_APP_INSTRUMENTATION_KEY" > .env.$NODE_ENV \
    && echo "REACT_APP_API_URL=$REACT_APP_API_URL" >> .env.$NODE_ENV

ARG ENVIRONMENT=prod
RUN npm run webpack:$ENVIRONMENT

RUN mv /tmp/build /app
WORKDIR /app

RUN echo "REACT_APP_INSTRUMENTATION_KEY=$REACT_APP_INSTRUMENTATION_KEY" > .env \
    && echo "REACT_APP_API_URL=$REACT_APP_API_URL" >> .env

ARG CORTEXIA_VERSION=0.0.0
ENV BUILDTIME_CORTEXIA_VERSION=$CORTEXIA_VERSION

EXPOSE 3000

CMD serve -s .
