version: "3.3"
services:
  vott:
    build:
      context: .
      args:
        - BUILDTIME_CORTEXIA_VERSION=${BUILDTIME_CORTEXIA_VERSION}
        - ENVIRONMENT=${ENVIRONMENT}
    image: cortexia/vott:${DOCKER_TAG}
    environment:
      - PUBLIC_URL=https://${SUBDOMAIN}.${DOMAIN}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - NODE_ENV=${NODE_ENV}
      - DEV_VOTT_PORT=${DEV_VOTT_PORT}
      - CORTEXIA_VERSION=${CORTEXIA_VERSION}
    deploy:
      labels:
        - traefik.frontend.rule=Host:${SUBDOMAIN}.${DOMAIN}
        - traefik.enable=true
        - traefik.port=${DEV_VOTT_PORT}
        - traefik.tags=${TRAEFIK_PUBLIC_TAG}
        - traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
